### ISSUE TITLE
Add array and dictionary literals

### ISSUE THREAD

**Issue by TyOverby** [TyOverby/ares#10]
Arrays have syntax `[a b c d]`

Dictionaries have syntax `{k1 v1 k2 v2}`

**Comment by TyOverby** [comment]
Excelent!  I think we can close this now?  Or do you have more work to do?

**Comment by bwo** [comment]
oh, I thought the issue would be closed when the PR was merged. :/
Excluding lists and maps as keys isn't in yet but I think it's ok for that to be separate.

**Comment by TyOverby** [comment]
That sounds reasonable.  

I think github closes issues if you explicitly write "closes #10" in the commit.
