### ISSUE TITLE
let, let* letrec?

### ISSUE THREAD

**Issue by TyOverby** [TyOverby/ares#18]
I'm thinking we do what clojure did and have a single `let` which acts like `let*`.

**Comment by bwo** [comment]
we could technically define let in terms of lambda, if we had macros. I don't know if we want this (or if we want macros, for that matter, but I have been thinking about adding quasi- and unquotation). But I agree that `let*` is generally simpler to grasp.

**Comment by TyOverby** [comment]
Closed in 8425e682f551a98c6da05527fd5f0586523f08a9
