### ISSUE TITLE
Macros

### ISSUE THREAD

**Issue by TyOverby** [TyOverby/ares#20]
I think macros would be really cool, and implementing them through `ast_fn`s shouldn't be too dificult.  We might want to hold off one macros until we have symbol interning though.

**Comment by bwo** [comment]
I would be happy to work on this but fyi I haven't been able to get as much done lately b/c my day job is demanding more time. Hopefully can do more on the weekend though.

**Comment by bwo** [comment]
knocked out a none-too-elegant quasiquotation impl; https://github.com/TyOverby/ares/tree/feat/quasiquotation

**Comment by bwo** [comment]
opened a pr

**Comment by TyOverby** [comment]
:tada:
