### ISSUE TITLE
probably don't want fexprs

### ISSUE THREAD

**Issue by bwo** [TyOverby/ares#35]
right now nothing prevents you from passing `quote` or other macro-like built-in functions around as arguments, resulting in potentially outcomes such as this repl session:

```
repl> (define foobar (lambda (f x) (f x)))
<@anonymous>
repl> (foobar quote 5)
'x
```

**Comment by TyOverby** [comment]
Oh yeah... That is really unfortunate.  

I can't think of an easy way to fix this without adding special cases specifically for the macro-like builtins that we don't want this to happen with.

**Comment by bwo** [comment]
I think the simplest (possibly not actually simple, but simplest) thing would be to just say that no `ast_fn` can have its value taken except as the head of a list being evaluated as a function call (like a macro, basically). Anything that needs to use the context to call functions can be a `user_fn`; the advantage of the `ast_fn` is that it receives its arguments unevaluated---like a macro---and that leads to all sorts of weirdness if they can be treated as normal values. That would require backing out the changes that unified the two under the hood, though. :/

**Comment by TyOverby** [comment]
Would it?  I'll play around with this tonight.  I think it might be a pretty easy change, but I haven't thought about it for very long.

**Comment by TyOverby** [comment]
Oh yep.  Totally removes the unification.  Dammit

**Comment by TyOverby** [comment]
Didn't end up being nearly as bad as I thought.  

This way, we could also go back and add fexprs at a later time if we wanted.

**Comment by TyOverby** [comment]
Using the context API, you can mess things up.
